//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsvBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        internal static string ActionAttribute {
            get {
                return ResourceManager.GetString("ActionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;Config&gt;
        ///  &lt;!-- Specify the source path. It can be a directory or a single file --&gt;
        ///  &lt;Source path=&quot;&quot; /&gt;
        ///  &lt;FileStrategy&gt;
        ///    &lt;!-- 
        ///      // Add one or more file strategy from Move and Copy
        ///      
        ///      &lt;Move path=&quot;&quot; overwrite=&quot;true|false|continue&quot; with=&quot;.txt,.tiff&quot; /&gt;
        ///      &lt;Copy path=&quot;&quot; overwrite=&quot;true|false|continue&quot; /&gt;
        ///    --&gt;
        ///  &lt;/FileStrategy&gt;
        ///  &lt;GroupedWith&gt;csv,tiff&lt;/GroupedWith&gt;
        ///  &lt;Directives&gt;
        ///    &lt;!--
        ///      // Add one or more dire [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string ConfigElement {
            get {
                return ResourceManager.GetString("ConfigElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.xml.
        /// </summary>
        internal static string ConfigFileName {
            get {
                return ResourceManager.GetString("ConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyElement {
            get {
                return ResourceManager.GetString("CopyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directives.
        /// </summary>
        internal static string DirectivesElement {
            get {
                return ResourceManager.GetString("DirectivesElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileStrategy.
        /// </summary>
        internal static string FileStrategyElement {
            get {
                return ResourceManager.GetString("FileStrategyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupedWith.
        /// </summary>
        internal static string GroupedWithElement {
            get {
                return ResourceManager.GetString("GroupedWithElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string MoveElement {
            get {
                return ResourceManager.GetString("MoveElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string NameAttribute {
            get {
                return ResourceManager.GetString("NameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overwrite.
        /// </summary>
        internal static string OverwriteAttribute {
            get {
                return ResourceManager.GetString("OverwriteAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path.
        /// </summary>
        internal static string PathAttribute {
            get {
                return ResourceManager.GetString("PathAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position.
        /// </summary>
        internal static string PositionAttribute {
            get {
                return ResourceManager.GetString("PositionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        internal static string RenameAttribute {
            get {
                return ResourceManager.GetString("RenameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        internal static string SeparatorElement {
            get {
                return ResourceManager.GetString("SeparatorElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string SourceElement {
            get {
                return ResourceManager.GetString("SourceElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string ToAttribute {
            get {
                return ResourceManager.GetString("ToAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        internal static string WithAttribute {
            get {
                return ResourceManager.GetString("WithAttribute", resourceCulture);
            }
        }
    }
}
